### ISSUE TITLE
【開発】画像マウスオーバー時アニメーションの修正

### ISSUE THREAD

**Issue by haueyne** [oppaitarou/transam#28]

**Comment by oppaitarou** [comment]
マウスオーバーで出すものに
・材料分量
・シェーク、ステア、ビルド
として、
画像の下にカクテル名　(度数)とかにした方が良いかなぁ？？
⇒テキーラサンライズ　(Alc 8.2％)

なんかもうちょいきれいにできそうな...

**Comment by oppaitarou** [comment]
マスター直接コミットして修正しました！
